version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-cricconect-api-gateway-localstack}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      - DEBUG=1
      - SERVICES=lambda,apigateway,dynamodb
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
